name: Lint CI

on:
  pull_request:
    branches: ["develop"]
  push:
    branches: ["develop"]

jobs:
  build:
    name: Lint
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 2.3.2

      - name: Run Biome
        run: biome check
